---
name: TEST
on: workflow_dispatch

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
    - name: test step1
      run: |
        echo "GITHUB_ACTION: $GITHUB_ACTION"
        echo "GITHUB_ACTION_PATH: $GITHUB_ACTION_PATH"
        echo "GITHUB_ACTOR: $GITHUB_ACTOR"
        echo "GITHUB_ACTOR_ID: $GITHUB_ACTOR_ID"
        echo "GITHUB_ENV: $GITHUB_ENV"
        echo "GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME"
        echo "GITHUB_JOB: $GITHUB_JOB"
        echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
        echo "GITHUB_WORKFLOW: $GITHUB_WORKFLOW"
        echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
        echo "RUNNER_ARCH: $RUNNER_ARCH"
        echo "RUNNER_NAME: $RUNNER_NAME"
        echo "RUNNER_OS: $RUNNER_OS"
        echo "github.repository: ${{github.repository}}"
        echo "github.event_name: ${{github.event_name}}"
        echo "github.workflow: ${{github.workflow}}"
        echo "github.ref: ${{github.ref}}"
    - name: test step2
      run: |
        echo "github.event: ${{toJSON(github.event)}}"
